blank_issues_enabled: true
contact_links:
  - name: Idea
    url: https://github.com/Brawaru/vue-intl-controller/discussions/new?category=ideas
    about: Propose an idea for the project
  - name: Question
    url: https://github.com/Brawaru/vue-intl-controller/discussions/new?category=questions
    about: Ask a question related to the project
